import './globals.css'
import { Anton } from 'next/font/google'

const anton = Anton({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={anton.className}>{children}</body>
    </html>
  )
}
